"""RAG evidence package: claims, citation locators, validation, and persistence."""

from margin.evidence.conflicts import EvidenceConflictClassifier
from margin.evidence.locator import (
    CitationLocator,
    LocatorReplayResult,
    LocatorValidationResult,
    LocatorValidator,
    PointInTimeCheckResult,
    SnapshotResolver,
    SourceType,
    WebSearchVerificationResult,
    build_locator_from_html,
    build_locator_from_pdf,
    build_locator_from_table,
    check_locators_point_in_time,
    check_point_in_time,
    validate_locator,
    verify_websearch_original,
)
from margin.evidence.models import (
    Claim,
    ClaimEvidenceLink,
    ClaimEvidenceRole,
    ClaimStatus,
    ClaimType,
    ConflictRecord,
    ConflictSeverity,
    Evidence,
    EvidenceConflict,
    EvidencePackage,
    EvidencePackageQualityStatus,
    FactOrInference,
    check_l5_restriction,
    detect_conflicts,
    make_claim,
    make_conflict,
    quality_score_for_level,
)
from margin.evidence.package_builder import EvidencePackageBuilder
from margin.evidence.repository import (
    EvidenceRepository,
    NewsContextEvidenceLink,
    ResearchEvidenceLink,
)
from margin.evidence.validator import (
    CitationValidator,
    FailReason,
    ValidationAuditor,
    ValidationAuditRecord,
    ValidationReport,
    ValidationResult,
    ValidationStatus,
    validate_claims_with_audit,
)

__all__ = [
    "CitationLocator",
    "CitationValidator",
    "Claim",
    "ClaimEvidenceLink",
    "ClaimEvidenceRole",
    "ClaimStatus",
    "ClaimType",
    "ConflictRecord",
    "ConflictSeverity",
    "Evidence",
    "EvidenceConflict",
    "EvidenceConflictClassifier",
    "EvidencePackage",
    "EvidencePackageBuilder",
    "EvidencePackageQualityStatus",
    "EvidenceRepository",
    "FactOrInference",
    "FailReason",
    "LocatorReplayResult",
    "LocatorValidationResult",
    "LocatorValidator",
    "NewsContextEvidenceLink",
    "PointInTimeCheckResult",
    "ResearchEvidenceLink",
    "SnapshotResolver",
    "SourceType",
    "ValidationAuditRecord",
    "ValidationAuditor",
    "ValidationReport",
    "ValidationResult",
    "ValidationStatus",
    "WebSearchVerificationResult",
    "build_locator_from_html",
    "build_locator_from_pdf",
    "build_locator_from_table",
    "check_l5_restriction",
    "check_locators_point_in_time",
    "check_point_in_time",
    "detect_conflicts",
    "make_claim",
    "make_conflict",
    "quality_score_for_level",
    "validate_claims_with_audit",
    "validate_locator",
    "verify_websearch_original",
]
