"""Migration verifier tests for deployment audit schema.

Verifies that the full Alembic migration sequence runs cleanly from an empty
database and produces the expected current schema head and table set.
"""

from __future__ import annotations

from sqlalchemy.engine import make_url

from scripts.verify_migrations import verify_clean_database


def test_migration_sequence_from_clean_database(database_url: str) -> None:
    """Test that the full migration sequence runs from a clean database.

    Args:
        database_url: str: .

    Returns:
        None: .
    """
    url = make_url(database_url)
    clean_database_name = f"{url.database}_migration_v02"

    result = verify_clean_database(
        database_url,
        database_name=clean_database_name,
        drop_existing=True,
    )

    assert result.current_head == result.expected_head
    assert result.failed_revision is None
    assert {
        "raw_meta.raw_data_snapshots",
        "raw_meta.raw_document_snapshots",
        "source_tushare.ods_daily_quote_raw",
        "source_akshare.ods_daily_quote_raw",
        "source_filing.raw_filings",
        "source_news.raw_articles",
        "source_doc.raw_documents",
        "vault.hub_security",
        "vault.hub_company",
        "vault.hub_source",
        "vault.hub_provider_endpoint",
        "vault.hub_document",
        "vault.hub_statement",
        "vault.hub_trading_calendar",
        "vault.hub_industry",
        "vault.hub_backfill_campaign",
        "vault.link_security_company",
        "vault.link_security_identifier",
        "vault.link_security_industry",
        "vault.link_security_daily_quote",
        "vault.link_security_financial_statement",
        "vault.link_security_document",
        "vault.link_security_corporate_action",
        "vault.link_stock_pool_membership",
        "vault.link_source_snapshot",
        "vault.sat_security_profile",
        "vault.sat_security_name_history",
        "vault.sat_identifier",
        "vault.sat_industry_membership",
        "vault.sat_listing_status",
        "vault.sat_daily_quote",
        "vault.sat_adjustment_factor",
        "vault.sat_daily_basic",
        "vault.sat_moneyflow",
        "vault.sat_margin_detail",
        "vault.sat_limit_status",
        "vault.sat_suspend_status",
        "vault.sat_financial_statement_income",
        "vault.sat_financial_statement_balance",
        "vault.sat_financial_statement_cashflow",
        "vault.sat_financial_indicator",
        "vault.sat_forecast",
        "vault.sat_express",
        "vault.sat_dividend",
        "vault.sat_corporate_action",
        "vault.sat_document_metadata",
        "vault.sat_document_text",
        "vault.sat_news_article",
        "vault.sat_document_embedding_metadata",
        "vault.pit_security_day",
        "vault.pit_financial_statement",
        "vault.pit_stock_pool_snapshot",
        "mart_dw.dim_date",
        "mart_dw.dim_stock",
        "mart_dw.dim_company",
        "mart_dw.dim_industry",
        "mart_dw.dim_source",
        "mart_dw.dim_provider_endpoint",
        "mart_dw.dim_document",
        "mart_dw.dim_factor",
        "mart_dw.dim_run",
        "mart_dw.dim_strategy",
        "mart_dw.dim_backfill_campaign",
        "mart_dw.daily_market_fact",
        "mart_dw.adjusted_price_fact",
        "mart_dw.daily_basic_fact",
        "mart_dw.moneyflow_fact",
        "mart_dw.margin_detail_fact",
        "mart_dw.financial_statement_fact",
        "mart_dw.financial_indicator_fact",
        "mart_dw.valuation_fact",
        "mart_dw.corporate_action_fact",
        "mart_dw.limit_suspend_fact",
        "mart_dw.stock_pool_membership_fact",
        "mart_dw.factor_fact",
        "mart_dw.document_coverage_fact",
        "mart_dw.news_sentiment_fact",
        "mart_dw.data_quality_fact",
        "mart.factor_panel",
        "mart.quant_candidate_mart",
        "mart.stock_analysis_mart",
        "mart.backtest_panel",
        "mart.company_profile_view",
        "app.dashboard_items_v2",
        "app.company_profile_page_v1",
        "app.agent_answer_context_v1",
        "app.data_freshness_panel_v1",
        "app.backfill_status_panel_v1",
        "app.research_run_trace_v1",
        "orchestration_runs",
        "orchestration_step_attempts",
        "transactional_outbox",
        "capacity_limit_versions",
        "quant_input_snapshots",
        "quant_screen_results",
        "effective_assessment_pointers",
        "news_refresh_runs",
        "news_refresh_targets",
        "document_security_links",
        "document_materiality_scores",
        "news_context_bundles",
        "news_context_documents",
        "indexed_documents",
        "chunk_security_links",
        "evidence_packages",
        "evidence_package_items",
        "claim_evidence_links",
        "evidence_conflicts",
        "news_context_evidence",
        "ai_graph_runs",
        "ai_graph_node_runs",
        "ai_graph_checkpoints",
        "tool_call_records",
        "llm_call_records",
        "research_delta_reviews",
        "research_delta_outbox",
        "data_acquisition_policy_versions",
        "quant_data_requirements",
        "provider_endpoint_requirements",
        "provider_endpoint_requirement_links",
        "source_quality_decisions",
        "source_akshare.ak_stock_zh_a_spot_em",
        "source_akshare.ak_stock_zh_a_hist",
        "source_akshare.ak_stock_balance_sheet_by_report_em",
        "source_akshare.ak_stock_value_em",
        "source_akshare.ak_index_stock_cons_csindex",
        "company_pool_snapshots",
        "company_pool_members",
        "analysis_snapshots",
        "analysis_metrics",
        "analysis_findings",
        "analysis_evidence_links",
        "quant_feature_snapshots",
        "quant_feature_rows",
        "news_agent_runs",
        "news_agent_tasks",
        "news_search_plans",
        "news_article_findings",
        "news_security_briefs",
        "agent_runtime_runs",
        "agent_runtime_steps",
        "agent_runtime_artifacts",
        "agent_runtime_guardrail_decisions",
        "agent_runtime_schedules",
        "agent_chat_sessions",
        "agent_chat_messages",
        "agent.context_packs",
        "agent.context_facts",
        "agent.context_omissions",
        "agent.domain_context_capsules",
        "agent.artifact_lineage_edges",
        "tool.tool_catalog_versions",
        "tool.tool_calls",
        "tool.tool_results",
        "tool.tool_rate_limit_buckets",
        "prompt.prompt_templates",
        "prompt.prompt_bundles",
        "prompt.prompt_render_history",
        "prompt.llm_call_audits",
        "platform.idempotency_keys",
        "platform.runtime_environments",
        "platform.config_resolution_snapshots",
        "platform.outbox_events",
        "platform.dead_letter_queue",
        "ops.backfill_campaigns",
        "ops.backfill_partitions",
        "ops.backfill_quality_reports",
        "ops.system_health_snapshots",
        "ops.data_freshness_states",
        "agent_flow_versions",
        "quant_agent_profile_versions",
        "config_resolution_snapshots",
        "config_resolution_snapshot_entries",
        "dashboard_runs",
        "dashboard_items",
        "source_tushare.ts_moneyflow",
        "source_tushare.ts_margin_detail",
        "source_tushare.ts_forecast",
        "source_tushare.ts_express",
        "source_tushare.ts_limit_list_d",
    } <= set(result.tables)
    assert {
        "portfolios",
        "trades",
        "position_theses",
        "alert_events",
        "position_reviews",
        "indicator_definitions",
        "provider_indicator_mappings",
        "universe_definitions",
        "universe_versions",
        "universe_snapshots",
        "universe_memberships",
        "research_refresh_events",
        "valuation_refresh_runs",
        "valuation_refresh_steps",
        "confidence_components",
        "idempotency_records",
        "smoke_run_records",
        "agent.runs",
        "agent.domain_tasks",
        "agent.worker_tasks",
        "agent.task_events",
        "agent.artifacts",
        "agent.audit_reports",
    }.isdisjoint(result.tables)
    assert result.pgvector_available is True
